# Generated by Django 5.2.6 on 2025-10-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_title_en_category_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(default='Серебро', max_length=30, null=True, verbose_name='Цвет/Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(default='Серебро', max_length=30, null=True, verbose_name='Цвет/Материал'),
        ),
    ]
